name: CI

on:
  push:
    branches: [main]

jobs:
  validate-and-publish:
    name: lint, test, build then publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup node and pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'

      - name: install dependencies
        run: pnpm install

      - name: lint
        run: pnpm run lint

      - name: test
        run: pnpm run test

      - name: build
        run: pnpm run build

      - name: check for changesets
        id: changesets
        run: |
          if pnpm exec changeset status | grep -q '☝️'; then
            echo "has_changesets=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_changesets=false" >> "$GITHUB_OUTPUT"
          fi

      - name: version & publish
        if: steps.changesets.outputs.has_changesets == 'true'
        run: |
          pnpm exec changeset version
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "version bump via changeset"
          git push
          pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
